baseURL: "http://maporo.ru/"
languageCode: "ru-ru"

title: "ООО МаПоРо"

summaryLength: 20

params:
  title: "ООО МаПоРо"
  description: "Разработка ПО любого уровня сложности."
  images: 
    - "images/service.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  location:
    - "236006, Калининградская область, г.Калининград, ул.Ю.Гагарина д.1 к.2 - 54"

  contact:
    - "ООО 'МаПоРо'"
    - "Разработка компьютерного программного обеспечения"
    - "info@maporo.ru"
    - "+79128636807"

  copyright: "© 2023 ООО МаПоРо"

menus:
  main:
    - name: "Главная"
      url: "/#landing"
      weight: 1

    - name: "Принципы"
      url: "/#principles"
      weight: 2

    - name: "Наша Команда"
      url: "/#team"
      weight: 3

    - name: "Наши Клиенты"
      url: "/#clients"
      weight: 4

    - name: "Контакты"
      url: "/#contacts"
      weight: 5

  footer:
    - name: "Главная"
      url: "/#landing"
      weight: 1

    - name: "Принципы"
      url: "/#principles"
      weight: 2

    - name: "Наша Команда"
      url: "/#team"
      weight: 3

    - name: "Наши Клиенты"
      url: "/#clients"
      weight: 4

    - name: "Контакты"
      url: "/#contacts"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
